#### ENVIRONMENT VARIABLES ####
@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}/
@api = api/v1/
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}


## Authentication
@pathAuth = {{api}}auth/
@email = trepichio@gmail.com
@password = Abc123456
### Login
# @name login
POST http://{{host}}{{pathAuth}}login HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### SAVE TOKEN TO ENVIRONMENT VARIABLE

@authToken = {{login.response.body.$.idToken.jwtToken}}


### Signup
# @name signup
POST http://{{host}}{{pathAuth}}signup HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "João",
  "email": "{{email}}",
  "password": "{{password}}",
  "mobilePhone": "+5512997123456"
}

## Players
@pathPlayers = {{api}}players/
@playerId = 61067ae8d57c244d9541dfbb
### Create players
# @name createPlayer
POST http://{{host}}{{pathPlayers}} HTTP/1.1
Content-Type: {{contentType}}
Authorization:Bearer {{authToken}}

{
  "name": "Jogador dois",
  "email": "p2@email.com",
  "mobileNumber": "12997456754",
  "category": "61068128d57c244d9541dfcd"
}

### Update a player
# @name updatePlayer
PUT http://{{host}}{{pathPlayers}}{{playerId}} HTTP/1.1
Content-Type: {{contentType}}
Authorization:Bearer {{authToken}}

{
  "name": "Jogador Um",
  "mobileNumber": "12997123456",
  "category": "60d631addd5122136a7c49ab"
}

### Get all players
@name getAllPlayers
GET http://{{host}}{{pathPlayers}} HTTP/1.1
Authorization:Bearer {{authToken}}

### Get a player
# @name getPlayer
GET http://{{host}}{{pathPlayers}}?playerId={{playerId}} HTTP/1.1
Authorization:Bearer {{authToken}}

### Upload a file to player profile
# @name uploadProfileFile
@fileName = your_file.jpg
@filePath = /path/to/your_file/{{fileName}}
@fileContentType = image/jpeg
POST http://{{host}}{{pathPlayers}}{{playerId}}/upload HTTP/1.1
Authorization:Bearer {{authToken}}
Host: {{host}}
Accept: {{contentType}}
Content-Type: multipart/form-data; boundary=*.*.*.*

--*.*.*.*
Content-Disposition: form-data; name="file"; filename="{{fileName}}"
Content-Type: {{fileContentType}}

< {{filePath}}
--*.*.*.*--

### Delete a player
# @name deletePlayer
DELETE http://{{host}}{{pathPlayers}}{{playerId}} HTTP/1.1
Authorization:Bearer {{authToken}}


## Categories
@pathCategories = {{api}}categories/
@categoryId = 60d631addd5122136a7c49ab
### Create Categories
# @name createCategory
POST http://{{host}}{{pathCategories}} HTTP/1.1
Content-Type: {{contentType}}
Authorization:Bearer {{authToken}}

{
  "category": "C",
  "description": "Category C",
  "events": [
    {
      "name": "Victory",
      "operation": "+",
      "value": 30
    },
    {
      "name": "Victory_Leader",
      "operation": "+",
      "value": 50
    },
    {
      "name": "Defeat",
      "operation": "+",
      "value": 0
    }
  ]
}

### Update a category by ID
# @name updateCategory
PUT http://{{host}}{{pathCategories}}{{categoryId}} HTTP/1.1
Content-Type: {{contentType}}
Authorization:Bearer {{authToken}}

{
  "description": "Category A",
  "events": [
    {
      "name": "Victory",
      "operation": "+",
      "value": 30
    },
    {
      "name": "Victory_Leader",
      "operation": "+",
      "value": 50
    },
    {
      "name": "Defeat",
      "operation": "+",
      "value": 0
    }
  ]
}

### Get all categories
# @name getAllCategories
GET http://{{host}}{{pathCategories}} HTTP/1.1
Authorization:Bearer {{authToken}}

### Get a category By ID
# @name getCategoryById
GET http://{{host}}{{pathCategories}}categories?categoryId={{categoryId}} HTTP/1.1
Authorization:Bearer {{authToken}}

### Delete a category
# @name deleteCategory
DELETE http://{{host}}{{pathCategories}}{{categoryId}} HTTP/1.1
Authorization:Bearer {{authToken}}
